#!/bin/bash

set -e

echo "-------------"
echo "DEPLOY SECTION"
echo "-------------"

source ${OPENSHIFT_REPO_DIR}/.openshift/action_hooks/common


echo "-------------"
echo "END DEPLOY SECTION"
echo "-------------"
