#!/bin/bash
function install_icu() {
    local pkg=icu4c-${ICU_VERSION//./_}-src.tgz




    pushd ${TMPDIR}

    echo "install_icu"${pkg}

    # Get archive
    #download_and_unpack ${pkg} http://download.icu-project.org/files/icu4c/${ICU_VERSION}/${pkg} icu

    wget -O ${pkg} http://download.icu-project.org/files/icu4c/${ICU_VERSION}/${pkg}

    tar -xvzf ${pkg}

    rm -rf ${pkg}

    pushd icu/source/

    echo "Configuring ICU."
    chmod +x runConfigureICU configure install-sh
    ./configure \
      --prefix=${OPENSHIFT_DIY_DIR}run/libs \
      --libdir=${OPENSHIFT_DIY_DIR}run/libs/lib64

    echo "Compiling ICU."
    make
    make install >> ${TMPDIR}icu4c-${ICU_VERSION//./_}.log

    pushd ${TMPDIR}

    rm -rf icu


}

function check_icu() {
    local icu_bin=${OPENSHIFT_DIY_DIR}run/libs/bin/icu-config
    if [[ ! -e  ${icu_bin} ]]; then
        echo "ICU not installed."
        install_icu
    else
        local icu_version=`${icu_bin} --version | tr -d '\n'`

        if [[ ${ICU_VERSION} != ${icu_version} ]]; then
            echo "ICU old, version: ${icu_version}."
            install_icu
        else
            echo "ICU up to date, version: ${icu_version}."
        fi
    fi
}
